/** Shapes returned by CoverClaim's views. Wei amounts arrive as decimal strings. */

export type Pool = {
  found?: boolean;
  pool_id: number;
  underwriter: string;
  protocol_name: string;
  llama_slug: string;
  llama_id: string;
  chain: string;
  perils: string[];
  exclusions: string[];
  evidence_allowlist: string[];
  payout_table_bps: number[];
  rate_bps: number;
  waiting_days: number;
  deductible_bps: number;
  max_cover_wei: string;
  term_days: number;
  collateral_bps: number;
  wording: string;
  policy_hash: string;
  created_at: number;
  expires_at: number;
  seconds_left: number;
  status: string;
  selling: boolean;
  closed_at: number;
  capital_wei: string;
  locked_wei: string;
  free_wei: string;
  utilization_bps: number;
  premiums_held_wei: string;
  premiums_earned_wei: string;
  deposited_wei: string;
  withdrawn_wei: string;
  refunded_wei: string;
  paid_out_wei: string;
  cover_count: number;
  active_covers: number;
  active_cover_wei: string;
  claim_count: number;
  books_wei: string;
};

export type Cover = {
  found?: boolean;
  cover_id: number;
  pool_id: number;
  protocol_name: string;
  llama_slug: string;
  buyer: string;
  amount_wei: string;
  premium_wei: string;
  lock_wei: string;
  days: number;
  bought_at: number;
  start: number;
  waiting_ends: number;
  end: number;
  claim_deadline: number;
  status: string;
  in_force: boolean;
  claimable: boolean;
  in_waiting_period?: boolean;
  claim_id: number;
  settled_at: number;
  refund_wei: string;
  payout_wei: string;
  backdated_days: number;
};

export type Claim = {
  found?: boolean;
  claim_id: number;
  cover_id: number;
  pool_id: number;
  protocol_name: string;
  claimant: string;
  underwriter: string;
  cover_amount_wei: string;
  cover_start: number;
  cover_end: number;
  waiting_ends: number;
  deductible_bps: number;
  filed_at: number;
  last_filed_at: number;
  incident_key: string;
  incident_id: string;
  evidence_urls: string[];
  statement: string;
  status: string;
  refiles: number;
  mismatch_refiles: number;
  mismatch_refiles_left: number;
  refile_until: number;
  attempts: number;
  stalls: number;
  judged_at: number;
  classification: string;
  event_match: string;
  effective: string;
  peril: string;
  exclusion: string;
  evidence_strength: number;
  strength_range: [number, number];
  incident_day: number;
  incident_date: string;
  protocol_match: boolean;
  evidence_binding: string;
  bound_pages: number;
  llama_record: string;
  tvl_window: string;
  tvl_before_usd: string;
  tvl_low_usd: string;
  drop_bps: number;
  severity_bucket: number;
  sources: number;
  bracket: string;
  pinned: string;
  model_called: boolean;
  content_hash: string;
  digest: string;
  reason: string;
  table_bps: number;
  gross_wei: string;
  payout_wei: string;
  batch_id: number;
  contest_window_closes: number;
  contestable_by: string;
  contest_status: string;
  contester: string;
  contest_bond_wei: string;
  contest_urls: string[];
  contest_statement: string;
  contested_at: number;
  contest_resolved_at: number;
  contest_classification: string;
  contest_effective: string;
  contest_peril: string;
  contest_exclusion: string;
  contest_strength: number;
  contest_bucket: number;
  contest_drop_bps: number;
  contest_content_hash: string;
  contest_novel: string;
  contest_reason: string;
  status_before_contest: string;
};

export type Batch = {
  found?: boolean;
  batch_id: number;
  pool_id: number;
  incident_day: number;
  incident_date: string;
  opened_at: number;
  closes_at: number;
  status: string;
  finalizable: boolean;
  finalized_at: number;
  members: number;
  claim_ids: number[];
  paid_members: number;
  gross_total_wei: string;
  available_wei: string;
  paid_total_wei: string;
  dust_wei: string;
  scaled: boolean;
};

export type Stats = {
  pools: number;
  open_pools: number;
  covers: number;
  claims: number;
  claims_by_status: Record<string, number>;
  judgements: number;
  judge_attempts: number;
  retries: number;
  contests: number;
  contests_flipped: number;
  batches_finalized: number;
  batches_scaled: number;
  refusals: number;
  capital_wei: string;
  locked_wei: string;
  unearned_premium_wei: string;
  bonds_wei: string;
  total_capacity_deposited_wei: string;
  total_premiums_wei: string;
  total_premiums_earned_wei: string;
  total_refunds_wei: string;
  total_payouts_wei: string;
  total_claimed_wei: string;
  balance_wei: string;
  held_wei: string;
  payable_wei: string;
  ledger_balanced: boolean;
  held_matches_books: boolean;
  chain_balance_wei: string;
  undelivered_wei: string;
  paused: boolean;
  owner: string;
  demo: boolean;
};

export type Config = {
  policy_version: string;
  demo: boolean;
  label: string;
  demo_backdate_days: number;
  owner: string;
  paused: boolean;
  now: number;
  claim_window_s: number;
  settlement_window_s: number;
  contest_window_s: number;
  stall_ttl_s: number;
  buy_cooldown_s: number;
  contest_bond_wei: string;
  perils: string[];
  exclusions: string[];
  peril_text: Record<string, string>;
  exclusion_text: Record<string, string>;
  severity_edges_bps: number[];
  default_payout_table_bps: number[];
  min_covered_strength: number;
  base_domains: string[];
  max_urls: number;
  min_capacity_wei: string;
  min_cover_wei: string;
  rate_bps_range: [number, number];
  max_waiting_days: number;
  default_waiting_days: number;
  max_deductible_bps: number;
  term_days_range: [number, number];
  min_collateral_bps: number;
  division_of_labour: string;
};

export type Quote = {
  ok: boolean;
  reason: string;
  premium_wei: string;
  premium_gen: string;
  lock_wei: string;
  free_wei: string;
  payout_by_bucket_wei: string[];
  start: number;
  waiting_ends: number;
  end: number;
  formula: string;
};

export type EvidenceCheck = {
  ok: boolean;
  reason: string;
  items: { url: string; ok: boolean; reason: string }[];
  allowlist: string[];
};

export type IncidentCheck = {
  ok: boolean;
  incident_key: string;
  incident_id: string;
  reason: string;
  llama_id: string;
  window: [string, string];
  format: string;
};

/** One row of api.llama.fi/hacks, as the claim form lists it. */
export type LlamaIncident = {
  key: string;
  date: string;
  name: string;
  classification: string;
  technique: string;
  amount: number;
};

export type Policy = { found: boolean; text: string; policy_hash: string; hash_matches: boolean };

export type Verification = {
  found: boolean;
  content_hash: string;
  recomputed_hash: string;
  hash_matches: boolean;
  severity_bucket: number;
  drop_bps: number;
  bucket_from_drop: number;
  table_bps: number;
  deductible_bps: number;
  cover_wei: string;
  gross_recomputed_wei: string;
  gross_stored_wei: string;
  payout_wei: string;
  formula: string;
};

export type WriteResult = {
  status: "OK" | "REJECTED" | "UNKNOWN";
  reason?: string;
  [key: string]: unknown;
};
